stages:
  process_data:
    cmd: python src/preprocess.py --input_path=data/raw 
      --output_path=data/processed/train.csv
    deps:
    - data/raw
    - src/preprocess.py
    outs:
    - data/processed/train.csv
  evaluate_model:
    cmd: python src/evaluate_model.py 
      --model_path=models/apartment_price_model.pkl 
      --preprocessor_path=models/preprocessor.pkl 
      --test_data_path=data/processed/train.csv
    deps:
    - data/processed/train.csv
    - models/apartment_price_model.pkl
    - models/preprocessor.pkl
    - src/evaluate_model.py
    outs:
    - reports/metrics.csv
    - reports/metrics.json
    - reports/metrics.txt
  train_model:
    cmd: python src/train_model.py --model_path=models/apartment_price_model.pkl
      --preprocessor_path=models/preprocessor.pkl 
      --input_path=data/processed/train.csv
    deps:
    - data/processed/train.csv
    - src/train_model.py
    outs:
    - models/apartment_price_model.pkl
    - models/preprocessor.pkl
